### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by rekado** [ZhengXia/dapars#10]
Rpy2 no longer supports Python 2.  The last version to support Python 2 does not support the latest version of R.  It seems that the best way forward is to upgrade dapars to Python 3.

**Comment by xxzzwan** [comment]
I couldn't agree more

**Comment by xxzzwan** [comment]
> Rpy2 no longer supports Python 2. The last version to support Python 2 does not support the latest version of R. It seems that the best way forward is to upgrade dapars to Python 3.

Hi, did you solve this Rpy2 problem? Cause it is 2020 and python 2 is shutting down and rpy2 cannot be supported. I've got the same problem with you as follow:

Traceback (most recent call last):
  File "./DaPars_main.py", line 11, in <module>
    from rpy2.robjects.packages import importr
ImportError: No module named rpy2.robjects.packages

So I 've got no idea to use dapars in python 2.7, searching for somebody's help. Thank you!

**Comment by gadiscymraes** [comment]
Hi, I have the same problem.
Did anyone find a solution?

Traceback (most recent call last):
  File "../src/dapars-master/src/DaPars_main.py", line 11, in <module>
    from rpy2.robjects.packages import importr
ModuleNotFoundError: No module named 'rpy2'

**Comment by xxzzwan** [comment]
Solved it by create a conda virtual environment with python 2. You may have a try!

**Comment by ZhengXia** [comment]
Thank you for the suggestion! DaPars 1.0.0 was migrated to Python 3!
