### ISSUE TITLE
Possible to install using conda?

### ISSUE THREAD

**Issue by maximus-sci** [ZhengXia/dapars#14]
Hello,

I'm trying to install dapars on a computing cluster and am unable to get it running. I'm trying to use it in a virtual environment with python 2.7, rpy2(v2.8.6) and r-base(v3.4.1). When I try to run the program I get:

`Traceback (most recent call last):
  File "/project/klynclab/software/dapars-0.9.1/src/DaPars_main.py", line 11, in <module>
    from rpy2.robjects.packages import importr
  File "/home/fmax/miniconda3/envs/dapars/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/home/fmax/miniconda3/envs/dapars/lib/python2.7/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: libicuuc.so.64: cannot open shared object file: No such file or directory
`

Can anyone give me a list of the dependencies/packages required to properly run dapars?

**Comment by slickmcfavorite42** [comment]
I solved this by generating a virtual environment for dapars using the attached .yaml file

(you'll have to rename it .yaml as that filetype is not allowed on github
[dapars.txt](https://github.com/ZhengXia/dapars/files/4623428/dapars.txt)

**Comment by ZhengXia** [comment]
DaPars 1.0.0 does not depend on rpy2 now!
