### ISSUE TITLE
Docs link broken?

### ISSUE THREAD

**Issue by grexor** [ZhengXia/dapars#15]
Hello, looks like the docs link is broken:

http://lilab.research.bcm.edu/dldcc-web/lilab/zheng/DaPars_Documentation/html/DaPars.html

Would like to use daPars but would need some examples / docs / install instructions.

Please advise,
Thanks,
Gregor

**Comment by sid-sethi** [comment]
Hello,

I have come across the same problem. The documentation link is broken. It would be great if you could fix it.

Many thanks,
Sid

**Comment by ZhengXia** [comment]
It is fiexed now.
